# 公共配置
spring:
  application:
    name: BiograFi-Backend
  # 默认激活开发环境
  profiles:
    active: dev
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 服务器配置
server:
  port: 5002
  servlet:
    context-path: /

# OpenAPI配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  info:
    title: BiograFi-Backend API
    description: 传记快线后端API文档
    version: 1.0.0
    contact:
      name: BiograFi Team
      email: biografi@example.com
    license:
      name: Apache 2.0
      url: http://springdoc.org

